---
name: "Update Flake"

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:

jobs:
  update-flake-lock:
    name: "Update Flake Lock"
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write
          repositories: "dots.factory,dots.vault"
      - name: Get GitHub App user info
        id: user-info
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          SLUG: ${{ steps.app-token.outputs.app-slug }}
        run: |
          name="${SLUG}[bot]"
          id=$(gh api "/users/$name" --jq .id)
          {
            echo "id=$id"
            echo "name=$name"
            echo "email=$id+$name@users.noreply.github.com"
          } >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Git
        env:
          GIT_USER_NAME: ${{ steps.user-info.outputs.name }}
          GIT_USER_EMAIL: ${{ steps.user-info.outputs.email }}
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v27
        env:
          NIX_CONFIG: "access-tokens = github.com=${{ steps.app-token.outputs.token }}"
        with:
          token: ${{ steps.app-token.outputs.token }}
          git-committer-name: ${{ steps.user-info.outputs.name || 'github-actions[bot]' }}
          git-committer-email: ${{ steps.user-info.outputs.email || '41898282+github-actions[bot]@users.noreply.github.com' }}
          git-author-name: ${{ steps.user-info.outputs.name || 'github-actions[bot]' }}
          git-author-email: ${{ steps.user-info.outputs.email || '41898282+github-actions[bot]@users.noreply.github.com' }}
          pr-body: |
            Automated update by the [update-flake-lock] GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

            This PR was most recently updated by workflow run [${{ github.run_id }}].

            [update-flake-lock]: https://github.com/DeterminateSystems/update-flake-lock
            [${{ github.run_id }}]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          pr-labels: |-
            merge-queue
